name: Test & Coverage

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
            apps/*/node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Run shared package tests with coverage
        run: |
          cd packages/shared
          bun run test:coverage

      - name: Build UI package
        run: |
          cd packages/ui
          bun run build

      - name: Run UI package tests with coverage
        run: |
          cd packages/ui
          bun run test:coverage

      - name: Run backend tests with coverage
        run: |
          cd apps/backend
          bun run test:coverage

      - name: Run frontend tests with coverage
        run: |
          cd apps/frontend
          bun run test:coverage

      - name: Cache test results
        uses: actions/cache@v4
        with:
          path: |
            packages/shared/coverage/
            packages/ui/coverage/
            apps/backend/coverage/
            apps/frontend/coverage/
          key: ${{ runner.os }}-test-results-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-test-results-

      - name: Upload shared package coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./packages/shared/coverage/lcov.info
          flags: shared
          name: shared-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload UI package coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./packages/ui/coverage/lcov.info
          flags: ui
          name: ui-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload backend coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./apps/backend/coverage/lcov.info
          flags: backend
          name: backend-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload frontend coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./apps/frontend/coverage/lcov.info
          flags: frontend
          name: frontend-coverage
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            packages/shared/coverage/
            packages/ui/coverage/
            apps/backend/coverage/
            apps/frontend/coverage/

      - name: Comment PR with coverage
        if: github.event_name == 'pull_request'
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: |
            packages/shared/coverage/lcov.info
            packages/ui/coverage/lcov.info
            apps/backend/coverage/lcov.info
            apps/frontend/coverage/lcov.info
          delete-old-comments: true
          github-token: ${{ secrets.CODECOV_TOKEN }}
          title: Coverage Report
